### ISSUE TITLE
[Issue]: Please key in at least one property or ensure a tag is selected

### ISSUE THREAD

**Issue by Saidelocha** [hkgnp/logseq-powertags-plugin#22]
### Plugin Version

1.04

### Logseq Version

0.9.10

### What browsers are you seeing the problem on?

MacOS

### What happened?

Hello,

I do exactly as the readme said. 
But I keep getting this error making the plugin completely useless.
I hope you can fix it, because you had a brillant idea very helpful.
Thank you in advance.

P.S: I've tried to enter the properties in the different ways below : 
- titre, directeur, acteurs
- titre,directeur,acteurs
- titre::,directeur::,acteurs::

Saidelocha

<img width="1099" alt="Capture d’écran 2023-07-06 à 10 56 13" src="https://github.com/hkgnp/logseq-powertags-plugin/assets/97402209/df7753f4-ccd4-49ea-8b82-4470c2dbfd34">

**Comment by dmil** [comment]
+1 also having this issue

**Comment by dmil** [comment]
Aha, looked in the code and based on this line, I tried using the "enter" key instead of clicking the "Save Properties" button with my mouse and it worked. (I used the syntax without the spaces - titre,directeur,acteurs)


https://github.com/hkgnp/logseq-powertags-plugin/blob/b8ad581549cb2295ce8d32fb7a8558008adbb046/src/components/CreateTag.tsx#L23

**Comment by dmil** [comment]
Ah, it looks like you have to press enter and THEN click the save properties function
